### ISSUE TITLE
'VERSION' was not declared in this scope   sprintf(tag, "OpenBTS %s Build Date %s", VERSION, __DATE__);

### ISSUE THREAD

**Issue by ibra1212** [fairwaves/openbts-2.8#13]
hello i'm working on openBTS 2.8 currently and when i put the make command i get this error:

make[2]: Entering directory `/home/openbts/openbts-2.8/SIP'
  CXX      SIPMessage.lo
SIPMessage.cpp: In function 'void openbts_message_init(osip_message_t**)':
SIPMessage.cpp:50:43: error: 'VERSION' was not declared in this scope
  sprintf(tag, "OpenBTS %s Build Date %s", VERSION, __DATE__saut 

can you help me or orient me on this problem?
